version: "3"

services:
  rust_dev:
    build: .
    image: ubuntu:22.04
    volumes:
      - type: bind
        source: ./workspace/
        target: /root/workspace/
        read_only: false
    stdin_open: true
    tty: true


