version: "3"

services:
  develop_kozos_custom:
    build: ./
    volumes:
      - type: bind
        source: ./workspace/
        target: /root/workspace/
        read_only: false
    stdin_open: true
    tty: true
